### ISSUE TITLE
Two Column layout for tablet portrait view

### ISSUE THREAD

**Issue by gumbopop** [beaverbuilder/feature-requests#52]
One of the biggest issue I have with BB is the column settings for tablet portrait view. It seems there is no option to set a 2 column layout for tablet portrait view.

This is a feature that is available in Elementor Wordpress builder plugin and would make a good feature for BB as this is the only draw back when building websites in BB for mobile devices.

It would be great to have a tablet portrait view option that shows the tablet view in portrait and to set the view in 2 column or 3 column layout and allow users to then organise the content to slot into the layout.

**Comment by gbissland** [comment]
@gumbopop  If I understand correctly you can just change your column widths to 50% to get 2 columns on any device.
https://docs.wpbeaverbuilder.com/beaver-builder/layouts/columns/prevent-column-stacking-with-custom-widths/

You can also change your breakpoints for the builder and theme to include the portrait view in the tablet breakpoint.
If you are looking at a regular ipad or an andriod tablet I think the common screen in portrait is 768 x 1024, If you adjust your small breakpoint in BB down from 768px tot 767px (or lower) you will get the tablet view (not mobile) which doesn't stack to 1 col by default.

https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/breakpoints-for-device-sizes

Good to also check your google analytics to see how many visitors are using their tablets in portrait rather than landscape.

**Comment by gumbopop** [comment]
Hi Gareth
Thanks for the advice.  I think this is half the problem, its not very clear that you can do this and how.

Regards

Las
